[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_marketplace_core = "3xhZuCq1ddQwWayATgBE1QFqjJ1BUyyXH4j73FJzbBgV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "TS_NODE_PROJECT=./tsconfig.json yarn run mocha -r ts-node/register -t 1000000 \"tests/**/*.ts\""

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
